### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by engharb** [pmill/aws-cognito#4]
Hello,

How can I implement Logout function? and isAuthenticated function?

regards,

**Comment by pmill** [comment]
Hello, for isAuthenticated functionality you can use the `verifyAccessToken` method.

The only logout method aws cognito api offers are the `GlobalSignOut` methods, however this signs the user out of all active sessions rather than just the current one, so it's probably not what you are looking for. However you can simply just 'forget' the authentication tokens you have in your app and require the user to login again to get new ones.
